%{
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define OUTPUT_FILE "output.xml"

void yyerror(const char *s);    /* reports syntax errors */
int yylex(void);                /* lexer function generated by Flex */

static char *result = NULL;     /* XML produced by a successful parse */
%}

/* Track line/column of every token (available as @n and yylloc). */
%locations

/* Error messages say what was found and what was expected. */
%define parse.error verbose

%union {
    char* str;
}

/* The quoted names are used in error messages instead of token names. */
%token <str> STRING   "string"
%token LBRACE         "{"
%token RBRACE         "}"
%token LBRACKET       "["
%token RBRACKET       "]"
%token COLON          ":"
%token COMMA          ","
%token INVALID        "invalid character"
%token UNTERMINATED   "unterminated string"

%type <str> pair_list pair value object array array_elements

/* If parsing fails halfway, Bison frees the strings already on its stack. */
%destructor { free($$); } <str>

%start json

%%

json:
    /* the whole JSON document is one object */
    object
    {
        /* only remember the result; main() writes it if parsing succeeded */
        result = $1;
    }
;

object:
    /* a JSON object is a list of key:value pairs */
    LBRACE pair_list RBRACE
    {
        $$ = $2;
    }
;

pair_list:
    /* one or more pairs separated by commas */
    pair
    {
        $$ = $1;
    }
    | pair COMMA pair_list
    {
        /* concatenate the XML produced by each pair */
        size_t len = strlen($1) + strlen($3) + 1;
        $$ = malloc(len);
        snprintf($$, len, "%s%s", $1, $3);
        free($1);
        free($3);
    }
;

pair:
    /* "key": value becomes <key>value</key> */
    STRING COLON value
    {
        size_t size = strlen($1) * 2 + strlen($3) + 20;
        $$ = malloc(size);
        snprintf($$, size, "  <%s>%s</%s>\n", $1, $3, $1);
        free($1);
        free($3);
    }
;

value:
    /* a value is a string, a nested object or an array */
    STRING  { $$ = $1; }
    | object  { $$ = $1; }
    | array   { $$ = $1; }
;

array:
    /* a JSON array is a list of values between square brackets */
    LBRACKET array_elements RBRACKET
    {
        $$ = $2;
    }
;

array_elements:
    /* each array element is wrapped in <item></item> */
    value
    {
        /* "<item>" (6) + "</item>" (7) + "\n" (1) + '\0' (1) = 15 */
        size_t len = strlen($1) + 15;
        $$ = malloc(len);
        snprintf($$, len, "<item>%s</item>\n", $1);
        free($1);
    }
    | value COMMA array_elements
    {
        size_t len = strlen($1) + strlen($3) + 15;
        $$ = malloc(len);
        snprintf($$, len, "<item>%s</item>\n%s", $1, $3);
        free($1);
        free($3);
    }
;

%%

/* Bison calls this on a syntax error; yylloc holds the offending token's position. */
void yyerror(const char *s)
{
    fprintf(stderr, "error at line %d, column %d: %s\n",
            yylloc.first_line, yylloc.first_column, s);
}

int main(void)
{
    if (yyparse() != 0) {
        /* don't leave output from a previous run that looks like a valid result */
        remove(OUTPUT_FILE);
        fprintf(stderr, "conversion failed, no output written\n");
        return 1;
    }

    FILE *f = fopen(OUTPUT_FILE, "w");
    if (!f) {
        perror("cannot create " OUTPUT_FILE);
        free(result);
        return 1;
    }

    fprintf(f, "<root>\n%s</root>\n", result);
    fclose(f);
    free(result);

    printf("XML written to %s\n", OUTPUT_FILE);
    return 0;
}